packages:
  - .

allowBuilds:
  esbuild: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - '@effect/platform-node-shared@4.0.0-rc.115'
  - '@effect/platform-node@4.0.0-rc.115'
  - '@effect/vitest@4.0.0-rc.115'
  - effect@4.0.0-rc.115

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

overrides:
  nanoid@<3.3.18: 3.3.19
